---
coredns_zone_files_paths:
- 'coredns/zones/*'
coredns_config_file: coredns/Corefile.primary.j2

noisebridge_dns_secondary_servers:
  # ns2.noisebridge.net (m4.noisebridge.net)
  - '2602:ff06:677:4:54::1337'
  - '204.246.122.84'

noisebridge_dns_primary_zones:
  - name: noisebridge.com
    file: noisebridge.com
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
  - name: noisebridge.io
    file: noisebridge.io
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
  - name: noisebridge.net
    file: noisebridge.net
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
    dnssec_key_file: 'Knoisebridge.net.+013+33211'
  - name: noisebridge.org
    file: noisebridge.org
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
  - name: noisetor.net
    file: noisetor.net
    transfer_to: "{{ noisebridge_dns_secondary_servers }}"
