---
coredns_config_file: coredns/Corefile.secondary.j2

noisebridge_dns_primary_servers:
  # ns1.noisebridge.net (m3.noisebridge.net)
  - '2602:ff06:725:5:dc::1337'
  - '216.252.162.220'

noisebridge_dns_seconary_zones:
  - name: noisebridge.com
    transfer_from: "{{ noisebridge_dns_primary_servers }}"
  - name: noisebridge.io
    transfer_from: "{{ noisebridge_dns_primary_servers }}"
  - name: noisebridge.net
    transfer_from: "{{ noisebridge_dns_primary_servers }}"
  - name: noisebridge.org
    transfer_from: "{{ noisebridge_dns_primary_servers }}"
  - name: noisetor.net
    transfer_from: "{{ noisebridge_dns_primary_servers }}"
