---
- name: Restart opendkim
  systemd:
    name: opendkim
    state: restarted

- name: Restart postfix
  systemd:
    name: postfix
    state: restarted

- name: Restart postgrey
  systemd:
    name: postgrey
    state: restarted

- name: Reload-aliases
  command: /usr/bin/newaliases

- name: Postmap-hash
  command: "/usr/sbin/postmap hash:/etc/postfix/{{ item.item }}"
  when: item.changed
  with_items: "{{ postfix_hash_maps.results }}"
