---
version: 2
updates:
  - directory: "/collections"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
  - directory: "/roles"
    package-ecosystem: "pip"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
