# Authoritative DNS with CoreDNS.
# Serves: noisebridge.net, noisebridge.com, noisebridge.io, noisebridge.org, noisetor.net
# DNSSEC enabled for noisebridge.net.
# Prometheus metrics on localhost:9153.
{ config, pkgs, lib, ... }:
let
  zoneDir = ../dns-zones;

  # DNSSEC key file basename — place the .key and .private files
  # in /var/lib/coredns/keys/ on the host before enabling DNSSEC.
  dnssecKeyFile = "Knoisebridge.net.+013+33211";

  # Secondary DNS servers allowed to pull zone transfers (AXFR).
  # Current m7 (ns2.noisebridge.net) — add/replace with new secondary as needed.
  secondaryServers = [
    "2600:3c0a::f03c:93ff:fe37:3d2f"
    "172.232.171.61"
  ];

  transferBlock = lib.concatMapStringsSep "\n" (s: "    to ${s}") secondaryServers;

  # Build the Corefile from the Ansible Corefile.primary.j2 template.
  corefile = ''
    # Noisebridge authoritative DNS — generated by NixOS
    noisebridge.net {
      prometheus localhost:9153
      errors
      file /var/lib/coredns/zones/noisebridge.net
      dnssec noisebridge.net {
        key file /var/lib/coredns/keys/${dnssecKeyFile}
      }
      transfer {
    ${transferBlock}
      }
    }

    noisebridge.com {
      prometheus localhost:9153
      errors
      file /var/lib/coredns/zones/noisebridge.com
      transfer {
    ${transferBlock}
      }
    }

    noisebridge.io {
      prometheus localhost:9153
      errors
      file /var/lib/coredns/zones/noisebridge.io
      transfer {
    ${transferBlock}
      }
    }

    noisebridge.org {
      prometheus localhost:9153
      errors
      file /var/lib/coredns/zones/noisebridge.org
      transfer {
    ${transferBlock}
      }
    }

    noisetor.net {
      prometheus localhost:9153
      errors
      file /var/lib/coredns/zones/noisetor.net
      transfer {
    ${transferBlock}
      }
    }
  '';
in
{
  services.coredns = {
    enable = true;
    config = corefile;
  };

  # Deploy zone files from the repo to /var/lib/coredns/zones/
  systemd.tmpfiles.rules = [
    "d /var/lib/coredns/zones 0755 coredns coredns -"
    "d /var/lib/coredns/keys  0700 coredns coredns -"
  ];

  # Copy zone files into place on activation
  system.activationScripts.coredns-zones = lib.stringAfter [ "etc" ] ''
    install -d -m 0755 -o coredns -g coredns /var/lib/coredns/zones
    for zone in ${zoneDir}/noisebridge.net ${zoneDir}/noisebridge.com ${zoneDir}/noisebridge.io ${zoneDir}/noisebridge.org ${zoneDir}/noisetor.net; do
      install -m 0644 -o coredns -g coredns "$zone" /var/lib/coredns/zones/
    done
  '';

  # Ensure the coredns user/group exist
  users.users.coredns = {
    isSystemUser = true;
    group = "coredns";
    home = "/var/lib/coredns";
  };
  users.groups.coredns = {};
}
