all:
  children:

# IO Cooperative Servers (m*.noisebridge.net)
# OS: Debian Stretch (Debian 9)
    m3_noisebridge_net:
      hosts:
        # Physical location: Santa Clara, California (IO Cooperative)
        m3.noisebridge.net: {}
    m4_noisebridge_net:
      hosts:
        # Physical location: Minneapolis, Minnesota (IO Cooperative)
        m4.noisebridge.net: {}
    m5_noisebridge_net:
      hosts:
        # Physical location: Santa Clara, California (IO Cooperative)
        m5.noisebridge.net: {}
    m6_noisebridge_net:
      hosts:
        # Physical location: Santa Clara, California (IO Cooperative)
        m6.noisebridge.net: {}
    m7_noisebridge_net:
      hosts:
        # Physical location: Seattle, Washington, USA (Linode)
        m7.noisebridge.net: {}

# Physical Servers located in Noisebridge (2169 Mission St., 3rd Floor)
    earl:
      hosts:
         earl.noise: {}
    smartpi:
      hosts:
        entropi.noise: {}
    space_noisebridge_net:
      hosts:
        # OS: Debian Stretch (Debian 9)
        pegasus.noisebridge.net: {}
    cloud:
      hosts:
        cloud.noise: {}

# Aliases (production)
    noisebridge_net:
      children:
        m3_noisebridge_net: {}
    donate_noisebridge_net:
      children:
        m5_noisebridge_net: {}
    library_noisebridge_net:
      children:
        m4_noisebridge_net: {}
    lists_noisebridge_net:
      children:
        m3_noisebridge_net: {}
    primary_dns_server:
      children:
        m3_noisebridge_net: {}
    secondary_dns_server:
      children:
        m7_noisebridge_net: {}
    dns:
      children:
        primary_dns_server: {}
        secondary_dns_server: {}

# Aliases (development)
    donate:
      children:
        m5_noisebridge_net: {}
