---
collections:
- name: community.general
  type: galaxy
  version: ">=12.3.0"
- name: ansible.posix
  type: galaxy
  version: ">=2.1.0"
- name: grafana.grafana
  type: galaxy
  version: ">=6.0.6"
- name: prometheus.prometheus
  type: galaxy
  version: ">=0.27.5"
- name: hifis.toolkit
  type: galaxy
  version: ">=6.3.2"
roles:
- name: caddy_ansible.caddy_ansible
  type: galaxy
  version: "v3.2.0"
