---

- name: node defaults
  hosts: all
  become: yes
  become_method: sudo
  tags: [common]
  roles:
    - utils
    - security
    - jnv.unattended-upgrades

- name: noisebridge-net
  hosts: noisebridge-net
  become: yes
  become_method: sudo
  tags: [noisebridge-net]
  roles:
    - antoiner77.caddy
    - mediawiki
    - cloudalchemy.node-exporter
    - cloudalchemy.prometheus
    - { role: mydumper, tags: [ 'mydumper' ] }
  vars:
    mediawiki:
      database: noisebridge_mediawiki
      database_username: wiki
      domain: noisebridge.net
      version_sha256sum: e2b2b9a68a6640c561dd9edb8fb594b738f8d5d6f97041a032072026460fc071
      version: 1.27.5

- name: List server
  hosts: lists-noisebridge-net
  become: yes
  become_method: sudo
  tags: [lists-noisebridge-net]
  roles:
    - postfix
    - mailman

- name: Primary DNS Server
  hosts: dns
  become: yes
  become_method: sudo
  tags: [dns]
  roles:
    - coredns

- name: Space
  hosts: space-noisebridge-net
  become: yes
  become_method: sudo
  tags: [space-noisebridge-net]
  roles:
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.snmp-exporter, tags: [ 'snmp' ] }
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - cloudalchemy.grafana
    - powerpanel
    
- name: Mailman-3 List server
  hosts: lists
  become: yes
  become_method: sudo
  tags: [lists]
  roles:
    - postfix
    - mailman3

- name: Nextcloud on debian box in space
  hosts: cloud
  become: yes
  become_method: sudo
  tags: [cloud]
  roles:
    - nextcloud-docker

- name: Parts service
  hosts: parts-noisebridge-net
  become: yes
  become_method: sudo
  tags: [parts-noisebridge-net]
  roles:
    - antoiner77.caddy
    - { role: stuff-org, tags: [ 'stuff-org' ] }
