---

- name: node defaults
  hosts: all
  become: yes
  become_method: sudo
  tags: [common]
  roles:
    - utils
    - security

- name: noisebridge-net
  hosts: noisebridge-net
  become: yes
  become_method: sudo
  tags: [noisebridge-net]
  roles:
    - antoiner77.caddy
    - mediawiki
  vars:
    mediawiki:
      database: noisebridge_mediawiki
      database_username: wiki
      domain: noisebridge.net
      version_sha256sum: 6ffac6baacf8a0c999e2d15d24631963efc242b4dab2f632d2614c539eea3976
      version: 1.27.4
    certbot_certs:
      m3.noisebridge.net:
        - m3.noisebridge.net

- name: List server
  hosts: lists-noisebridge-net
  become: yes
  become_method: sudo
  tags: [lists-noisebridge-net]
  roles:
    - postfix
    - mailman

- name: DNS Server
  hosts: primary-dns-server
  become: yes
  become_method: sudo
  tags: [primary-dns-server]
  roles:
    - coredns
