---

- name: Version precheck
  hosts: all
  gather_facts: False
  tags:
  - always
  pre_tasks:
  - name: Verify Ansible meets version requirements.
    assert:
      that: "ansible_version.full is version_compare('2.8', '>=')"
      msg: >
        "You must update Ansible to at least 2.8."

# Workaround for https://github.com/ansible/ansible/issues/57529
- hosts: all

- name: node defaults
  hosts: all
  become: yes
  become_method: sudo
  tags: [common]
  roles:
    - utils
    - security
    - jnv.unattended-upgrades
    - { role: motd, tags: [ 'motd' ] }

- name: noisebridge_net
  hosts: noisebridge_net
  become: yes
  become_method: sudo
  tags: [noisebridge_net]
  roles:
    - { role: mediawiki, tags: [ 'mediawiki' ] }
    - { role: website, tags: [ 'website' ] }
    - { role: safespace, tags: [ 'safespace' ] }
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.blackbox-exporter, tags: [ 'blackbox' ] }
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - { role: mydumper, tags: [ 'mydumper' ] }
    - { role: caddy, tags: [ 'caddy' ] }

- name: donate_noisebridge_net
  hosts: donate_noisebridge_net
  become: yes
  become_method: sudo
  tags: [donate]
  roles:
    - donate
    - percona
    - geerlingguy.mysql
    - { role: caddy, tags: [ 'caddy' ] }
    - { role: pydonate, tags: ['pydonate'] }

- name: List server
  hosts: lists_noisebridge_net
  become: yes
  become_method: sudo
  tags: [lists_noisebridge_net]
  roles:
    - postfix
    - mailman

- name: DNS Servers
  hosts: dns
  become: yes
  become_method: sudo
  tags: [dns]
  roles:
    - cloudalchemy.coredns

- name: Space
  hosts: space_noisebridge_net
  become: yes
  become_method: sudo
  tags: [space_noisebridge_net]
  roles:
    - cloudalchemy.node-exporter
    - { role: cloudalchemy.snmp-exporter, tags: [ 'snmp' ] }
    - { role: unifi-poller, tags: [ 'unifi-poller' ] }
    - { role: cloudalchemy.prometheus, tags: [ 'prometheus' ] }
    - cloudalchemy.grafana
    - powerpanel

- name: Nextcloud on debian box in space
  hosts: cloud
  become: yes
  become_method: sudo
  tags: [cloud]
  roles:
    - nextcloud-docker

- name: Earl RFID Access
  hosts: earl
  become: yes
  become_method: sudo
  tags: [earl]
  roles:
    - earl

- name: Power monitoring
  hosts: smartpi
  tags: [smartpi]
  roles:
    - smartpi

- name: Misc server SCL
  hosts: m6_noisebridge_net
  become: yes
  become_method: sudo
  tags: [m6_noisebridge_net]
  roles:
    - { role: podman, tags: ['podman'] }
    - { role: caddy, tags: [ 'caddy' ] }
    - { role: library-org, tags: [ 'library-org' ] }
    - { role: stuff-org, tags: [ 'stuff-org' ] }
