---
- name: Reload pydonate service file
  systemd:
    name: pydonate
    state: started
    enabled: true
    daemon_reload: true
- name: Restart pydonate
  systemd:
    name: pydonate
    state: restarted
