---
- name: Allow firewall
  community.general.ufw:
    rule: allow
    name: WWW Full

- name: Install
  ansible.builtin.include_role:
    name: caddy-ansible.caddy-ansible

- name: Format Caddyfile
  ansible.builtin.command:
    cmd: caddy fmt --overwrite /etc/caddy/Caddyfile
  changed_when: false

- name: Install jq
  become: true
  ansible.builtin.package:
    name: jq

- name: Adjust certs
  ansible.builtin.include_tasks:
    file: certs.yml
  tags:
    - caddy_certs
