---
- name: Add user
  ansible.builtin.user:
    name: "{{ item }}"
    comment: "{{ security_users_directory[item].fullname }}"
    shell: "{{ security_users_directory[item].shell | default('/bin/bash') }}"
  loop: "{{ security_admins + security_users | flatten | unique }}"
  tags:
    - access

- name: Grant sudo
  ansible.builtin.user:
    name: "{{ item }}"
    groups:
      - "sudo"
    append: true
  loop: "{{ security_admins | flatten | unique }}"
  tags:
    - access

- name: GitHub SSH key
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    key: "https://github.com/{{ security_users_directory[item].github_username }}.keys"
  loop: "{{ security_admins + security_users | flatten | unique }}"
  when: security_users_directory[item].github_username is defined
  tags:
    - access

- name: Static SSH key
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    key: "{{ security_users_directory[item].ssh_key }}"
  loop: "{{ security_admins + security_users | flatten | unique }}"
  when: security_users_directory[item].ssh_key is defined
  tags:
    - access
