---
- name: Install key
  ansible.builtin.apt_key:
    url: https://golift.io/gpgkey

- name: Setup repo
  ansible.builtin.apt_repository:
    repo: "deb https://dl.bintray.com/golift/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} {{ unifi_poller_apt_release }}"
    update_cache: true

- name: Install
  ansible.builtin.apt:
    name: "unifi-poller={{ unifi_poller_version }}"

- name: Configure
  ansible.builtin.template:
    src: up.conf.j2
    dest: /etc/unifi-poller/up.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart unifi-poller
