---
mediawiki:
  database: wiki
  database_username: wiki
  domain: example.com
  system_group: wiki
  system_user: wiki
mediawiki_composer:
  require:
mediawiki_version: 1.39.13
mediawiki_version_checksum: bb700c09792ece0877181a174c1687389d3dff93c8a5f39f81ba7509bdebecd6
