#!/bin/sh

php maintenance/install.php \
    --dbuser {{ mediawiki.database_username }} \
    --dbname {{ mediawiki.database }} \
    --dbpass {{ mysql_users|selectattr('name', 'equalto', mediawiki.database_username)|map(attribute='password')|join('') }} \
    --confpath "/srv/{{ mediawiki.domain }}/wiki" \
    --pass "{{ mediawiki_admin_password }}" \
    Noisebridge Patrickod
