---
security_admins: "{{ noisebridge_admins | default([]) }}"
security_users: "{{ noisebridge_users | default([]) }}"
security_users_directory: "{{ users | default([]) }}"
noisebridge_host_firewall: []
