---
- name: Add SURY keyring
  ansible.builtin.apt:
    deb: https://packages.sury.org/debsuryorg-archive-keyring.deb

- name: Setup SURY PHP apt repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/debsuryorg-archive-keyring.gpg] https://packages.sury.org/php/ {{ ansible_lsb.codename }} main"

- name: Install php
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    package:
      - imagemagick
      - php8.2
      - php8.2-mysql
      - php8.2-imagick
      - php8.2-fpm
      - php8.2-mbstring
      - php8.2-xml
      - composer
  tags:
    - apt
    - php

- name: Configure PHP FPM
  ansible.builtin.copy:
    src: php/www.conf
    dest: /etc/php/8.2/fpm/pool.d/www.conf
    mode: "0644"
  tags:
    - php
  notify:
    - restart php8.2-fpm
