---
library_org_version: "2.0.1"
# Path the legacy systemd-based deployment used; only read from for sqlite seed.
library_org_legacy_src_path: /srv/library-org
library_org_path: /srv/library.noisebridge.net
library_org_port: 5000
library_org_config:
  secrets:
    app_secret_key: nope
    wtf_csrv_secret_key: nope
    new_isbn_submit_seret: nope
    new_location_submit_secret: nope
    recaptcha_public_key: nope
    recaptcha_private_key: nope
