---
- name: Install memcached
  apt:
    package: memcached
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - memcached

- name: Start memcached
  systemd:
    name: memcached
    state: started
    enabled: true
  tags:
    - memcached
